#!/bin/bash

sleep 1

simpleFoam -postProcess -func wallShearStress -latestTime > log.wallShearStress
simpleFoam -postProcess -func R -latestTime

rm -fv system/sampleDict
cd system
ln -s sampleDict_velocityProfile sampleDict
cd ..
postProcess -func sampleDict -latestTime
cd system
rm -fv sampleDict
ln -s sampleDict_wallShearStress sampleDict
cd ..
postProcess -func sampleDict -latestTime

