#!/bin/bash

sleep 1

simpleFoam -postProcess -func wallShearStress -latestTime > log.wallShearStress
simpleFoam -postProcess -func R -latestTime

rm -fv system/sampleDict
cd system
ln -s sampleDict_velocityProfile sampleDict
cd ..
postProcess -func sampleDict -latestTime
cd system
rm -fv sampleDict
ln -s sampleDict_wallShearStress sampleDict
cd ..
postProcess -func sampleDict -latestTime

rm -r 4* 5* 6* 7* 8* 9* 3000 2000 1000 11* 12* 13* 14* 15* 16* 17* 18* 19*
